name: Push Docker image to Registry
on:
    release:
        types: [published]
jobs:
    push_to_registry:
        name: Push Docker image to Registry
        runs-on: self-hosted
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to Registry
              uses: docker/login-action@v1
              with:
                  registry: registry.randomphp.com
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - name: Build Image and push to Registry
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: registry.randomphp.com/mmsm/cron:latest